PracticalThirteen/Controllers/DesignationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PracticalThirteen.Data.Contexts;
using PracticalThirteen.Data.Models;

namespace PracticalThirteen.Controllers
{
    public class DesignationsController : Controller
    {
        private OrganizationDBContext _db;

        public DesignationsController(OrganizationDBContext db)
        {
            _db = db;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var data = await _db.Designations.ToListAsync();
            return View(data);
        }

        [HttpGet]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null) return View("Error/404");
            Designation? designation = await _db.Designations.FindAsync(id);
            if (designation == null) return View("Error/404");
            return View(designation);
        }

        // GET: Designations/Create
        public ActionResult Create()
        {
            return View(new Designation());
        }

        // POST: Designations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Designation designation)
        {
            if (ModelState.IsValid)
            {
                _db.Designations.Add(designation);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(designation);
        }

        // GET: Designations/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("Error");
            }
            Designation? designation = await _db.Designations.FindAsync(id);
            if (designation == null)
            {
                return View("Error");
            }
            return View(designation);
        }

        // POST: Designations/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Designation designation)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(designation).State = EntityState.Modified;
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(designation);
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null) return View("Error");
            Designation? designation = await _db.Designations.FindAsync(id);
            if (designation == null) return View("Error");
            return View(designation);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Designation? designation = await _db.Designations.FindAsync(id);
            if (designation == null) return View("Error/404");
            _db.Designations.Remove(designation);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PracticalThirteen/Views/Designations/Create.cshtml
@using PracticalThirteen.Data.Models;
@model Designation

@{
    ViewBag.Title = "Create";
}

<div class="container my-4">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.DesignationName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DesignationName, new { htmlAttributes = new { @class = "form-control",@placeholder = "Add Designation.." } })
                    @Html.ValidationMessageFor(model => model.DesignationName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mt-3">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index", "Designations", String.Empty, new { @class = "btn btn-danger mt-3" })
    </div>
</div>

PracticalThirteen/Views/Designations/Delete.cshtml
@model PracticalThirteen.Data.Models.Designation;

@{
    ViewBag.Title = "Delete";
}


<div class="container mt-5">
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 col-lg-4">
            <div class="card">
                @using (Html.BeginForm())
                {
                    <div class="card-body">
                        <h4 class="card-title text-center mb-3">Do you want to delete?</h4>

                        @Html.AntiForgeryToken()
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.DesignationName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.DesignationName)
                        </dd>

                    </dl>


                    </div>
                    <div class="card-footer text-muted d-flex justify-content-between bg-transparent border-top-0">
                        <div class="views">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                        </div>

                        <div class="stats">
                            @Html.ActionLink("Back to List", "Index", "Designations", String.Empty, new { @class = "btn btn-success" })
                        </div>

                    </div>
                }
            </div>
        </div>
    </div>
</div>

PracticalThirteen/Views/Designations/Details.cshtml
@model PracticalThirteen.Data.Models.Designation

@{
    ViewBag.Title = "Details";
}

<div class="container mt-5">
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 col-lg-4">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title text-center mb-3">Designation Details</h4>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.DesignationName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.DesignationName)
                        </dd>

                    </dl>
                </div>
                <div class="card-footer text-muted d-flex justify-content-between bg-transparent border-top-0">
                    <div class="views">
                        <a asp-controller="Designations" asp-action="Edit" class="btn btn-primary">Edit</a>
                        
                    </div>
                    <div class="stats">
                        <a asp-controller="Designations" asp-action="Index" class="btn btn-primary">Back to List</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PracticalThirteen/Views/Designations/Edit.cshtml
@model PracticalThirteen.Data.Models.Designation

@{
    ViewBag.Title = "Edit";
}

<div class="container mt-3">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.DesignationName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DesignationName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DesignationName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mt-3">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index", "Designations", String.Empty, new { @class = "btn btn-danger mt-3" })
    </div>
</div>

PracticalThirteen/Views/Designations/Index.cshtml
@model IEnumerable<PracticalThirteen.Data.Models.Designation>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p class="my-4">
    @Html.ActionLink("Create New", "Create", string.Empty, htmlAttributes: new { @class = "btn btn-primary" })
</p>
<table class="table" style="border-radius:10px !important;">
    <tr class="text-center ">
        <th>
            @Html.DisplayNameFor(model => model.DesignationName)
        </th>
        <th>Actions</th>
    </tr>

@foreach (var item in Model) {
    <tr class="text-center">
        <td>
            @Html.DisplayFor(modelItem => item.DesignationName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, htmlAttributes: new { @class = "btn " })
            @Html.ActionLink("Details", "Details", new { id = item.Id }, htmlAttributes: new { @class = "btn " })
            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, htmlAttributes: new { @class = "btn " })
        </td>
    </tr>
}
    <tr class="text-center">
        <td ><strong>Total Designation : </strong></td>
        <td ><strong>@Model.Count()</strong></td>
    </tr>

</table>